### ISSUE TITLE
Cannot link to contact page

### ISSUE THREAD

**Issue by QiLinXue** [RetroCraft/volunteeringpeel#28]
I don't think this is the same issue as  #18  as no description was provided. 

In the pages: /FAQ, /About, and /Homepage, the "contact page" hyperlink redirects users to the home page. The code:

`<Link to="/events">events page</Link>`

redirects users to /contact which does not exist. The actual contact form is located at /about/contact

**Comment by RetroCraft** [comment]
Yeah #18 is the finish making the contact page work issue.

Fix pushed.
