### ISSUE TITLE
Seperate Mailing List for Newsletter and Event Notifs

### ISSUE THREAD

**Issue by QiLinXue** [RetroCraft/volunteeringpeel#33]
Currently, there only exists one mailing list (newsletter), where the user can sign up on their profile page and on the home page.

There needs to be two mailing lists: one for the newsletter, and one for event notifications. The user should be able to sign up for event notifications both on their user page and on /events. See: http://volunteeringpeel.org/events.php for where it should be located.

**Comment by RetroCraft** [comment]
Do you want to collect names for both signups? Legacy site `/events.php` does but `/` doesn't.
