### ISSUE TITLE
Add Waiver

### ISSUE THREAD

**Issue by QiLinXue** [RetroCraft/volunteeringpeel#35]
In the faq page, the waiver currently redirects to the main website: http://volunteeringpeel.org/waiver.php

A waiver needs to be created, and should be linked there instead.

**Comment by RetroCraft** [comment]
I'll add a `/legal` page for ToC, Privacy Policy, Cookie Policy, and Waiver.

Google Analytics requires you to have stuff like that (we get away with it though because Google isn't auditing sites that don't get millions of views)
